# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ba398d0607bc07ef8dc6ad78ad154a3be652cb8459ad3a5b6ffdc6b0f93cd902ff1698df11e93650baa8cdd0a16b04861c1fa097545fa75e55071cfe13800a44

test:
  secret_key_base: a097be492724c4df2c53c41f85bffc69d68f08fa424b362d510be48d0478042cec757a1314eb08a50f311527eb070024951a281a50fdd888ae40e9527ecf64e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
